name: KiBot Tailboard

on:
  workflow_dispatch:
  push:
    paths:
      - "Tailboard/*.kicad_sch"
      - "Tailboard/*.kicad_pcb"
      - "Tailboard/*.kicad_pro"
      - "kibot.yml"
      - ".github/workflows/kibot-tailboard.yml"
      - ".github/workflows/kibot-base.yml"
  pull_request:
    paths:
      - "Tailboard/*.kicad_sch"
      - "Tailboard/*.kicad_pcb"
      - "Tailboard/*.kicad_pro"
      - "kibot.yml"
      - ".github/workflows/kibot-tailboard.yml"
      - ".github/workflows/kibot-base.yml"

jobs:
  call-base-workflow:
    uses: ./.github/workflows/kibot-base.yml
    with:
      config-file: Tailboard/BloopBox Tailboard.kicad_pcb
